---

- name: Configure PHP CLI
  ini_file:
    dest=/etc/php5/cli/conf.d/mailcatcher.ini
    section="mail function"
    option=sendmail_path
    value="/usr/bin/env /opt/ruby-1.9.3-p545/bin/catchmail"
  sudo: yes

- name: Configure PHP apache2
  ini_file:
    dest=/etc/php5/apache2/conf.d/mailcatcher.ini
    section="mail function"
    option=sendmail_path
    value="/usr/bin/env /opt/ruby-1.9.3-p545/bin/catchmail"
  sudo: yes
